name: cbvsa_inspecciones
description: App de inspecciones para CBVSA
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.5.6
  image_picker: ^1.1.2
  uuid: ^4.4.2
  path: ^1.9.0
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
