-- CBVSA · Inspecciones compartidas con autoría y auditoría
-- IMPORTANTE: ejecutar únicamente después de respaldar la base y Storage.
begin;

alter table public.inspections
  add column if not exists last_editor_id uuid references auth.users(id),
  add column if not exists last_editor jsonb,
  add column if not exists updated_at timestamptz not null default now();

create index if not exists inspections_inspector_id_idx on public.inspections(inspector_id);
create index if not exists inspections_updated_at_idx on public.inspections(updated_at desc);

create table if not exists public.inspection_audit (
  id bigint generated by default as identity primary key,
  inspection_id uuid not null,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  changed_by uuid references auth.users(id),
  changed_at timestamptz not null default now(),
  old_data jsonb,
  new_data jsonb
);

alter table public.inspection_audit enable row level security;

create or replace function public.protect_inspection_authorship()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if tg_op = 'UPDATE' then
    new.inspector_id := old.inspector_id;
    new.inspector := old.inspector;
    new.updated_at := now();
  end if;
  return new;
end;
$$;

create or replace function public.audit_inspection_change()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.inspection_audit(inspection_id, action, changed_by, old_data, new_data)
  values (
    coalesce(new.id, old.id), tg_op, (select auth.uid()),
    case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) end,
    case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) end
  );
  return coalesce(new, old);
end;
$$;

drop trigger if exists inspections_protect_authorship on public.inspections;
create trigger inspections_protect_authorship
before update on public.inspections for each row execute function public.protect_inspection_authorship();

drop trigger if exists inspections_audit_change on public.inspections;
create trigger inspections_audit_change
after insert or update or delete on public.inspections for each row execute function public.audit_inspection_change();

alter table public.inspections enable row level security;

-- Sustituye las políticas actuales de inspections por un conjunto consistente.
do $$
declare policy_name text;
begin
  for policy_name in select policyname from pg_policies where schemaname='public' and tablename='inspections'
  loop execute format('drop policy if exists %I on public.inspections', policy_name); end loop;
end $$;

create policy "team_can_read_inspections" on public.inspections
for select to authenticated using (true);

create policy "inspectors_create_as_themselves" on public.inspections
for insert to authenticated with check ((select auth.uid()) = inspector_id);

create policy "team_can_update_inspections" on public.inspections
for update to authenticated using (true) with check (true);

create policy "author_or_admin_can_delete_inspections" on public.inspections
for delete to authenticated using (
  inspector_id = (select auth.uid()) or exists (
    select 1 from public.profiles p where p.id = (select auth.uid()) and p.role = 'admin'
  )
);

drop policy if exists "team_can_read_audit" on public.inspection_audit;
create policy "team_can_read_audit" on public.inspection_audit
for select to authenticated using (true);

revoke insert, update, delete on public.inspection_audit from anon, authenticated;
grant select on public.inspection_audit to authenticated;

commit;

-- Verificación posterior (debe devolver RLS activo):
-- select relname, relrowsecurity from pg_class where relname in ('inspections','inspection_audit');

